/**
 * Codes pays de results.first.global (FRA, CHN…) → noms officiels des équipes.
 * Le collecteur les recopie dans data.json (champ « teams ») ; la page s'en sert
 * aussi directement si data.json ne les contient pas.
 */
export const TEAM_CODES = Object.freeze({
  AFG: "Afghanistan",
  ALB: "Albania",
  ALG: "Algeria",
  ANG: "Angola",
  ANT: "Antigua and Barbuda",
  ARG: "Argentina",
  ARU: "Aruba",
  ASA: "American Samoa",
  AUS: "Australia",
  AUT: "Austria",
  AZE: "Azerbaijan",
  BAN: "Bangladesh",
  BAR: "Barbados",
  BEL: "Belgium",
  BEN: "Benin",
  BHU: "Bhutan",
  BIH: "Bosnia and Herzegovina",
  BIZ: "Belize",
  BLR: "Belarus",
  BOL: "Bolivia",
  BOT: "Botswana",
  BRA: "Brazil",
  BRU: "Brunei Darussalam",
  BUL: "Bulgaria",
  BUR: "Burkina Faso",
  CAF: "Central African Republic",
  CAM: "Cambodia",
  CAN: "Canada",
  CAY: "Cayman Islands",
  CGO: "Congo",
  CHA: "Chad",
  CHI: "Chile",
  CHN: "China (People's Republic of)",
  CIV: "Côte d'Ivoire",
  CMR: "Cameroon",
  COD: "Congo (Democratic Republic of the)",
  COK: "Cook Islands",
  COL: "Colombia",
  COM: "Comoros",
  CPV: "Cabo Verde",
  CRC: "Costa Rica",
  CRO: "Croatia",
  CUB: "Cuba",
  CZE: "Czechia",
  DEN: "Denmark",
  DJI: "Djibouti",
  DMA: "Dominica",
  DOM: "Dominican Republic",
  ECU: "Ecuador",
  EGY: "Egypt",
  ERI: "Eritrea",
  ESA: "El Salvador",
  ESP: "Spain",
  EST: "Estonia",
  ETH: "Ethiopia",
  FIJ: "Fiji",
  FIN: "Finland",
  FRA: "France",
  FSM: "Micronesia (Federated States of)",
  GAB: "Gabon",
  GAM: "Gambia",
  GBR: "Great Britain",
  GBS: "Guinea-Bissau",
  GEO: "Georgia",
  GEQ: "Equatorial Guinea",
  GER: "Germany",
  GHA: "Ghana",
  GRE: "Greece",
  GRN: "Grenada",
  GUA: "Guatemala",
  GUI: "Guinea",
  GUM: "Guam",
  GUY: "Guyana",
  HAI: "Haiti",
  HKG: "Hong Kong (China)",
  HON: "Honduras",
  HPE: "Hope (Refugees)",
  HUN: "Hungary",
  INA: "Indonesia",
  IND: "India",
  IRI: "Iran (Islamic Republic of)",
  IRL: "Ireland",
  IRQ: "Iraq",
  ISR: "Israel",
  ISV: "Virgin Islands (U.S.)",
  ITA: "Italy",
  IVB: "Virgin Islands (British)",
  JAM: "Jamaica",
  JOR: "Jordan",
  JPN: "Japan",
  KAZ: "Kazakhstan",
  KEN: "Kenya",
  KGZ: "Kyrgyzstan",
  KIR: "Kiribati",
  KOR: "Korea (Republic of)",
  KOS: "Kosovo",
  LAO: "Lao People's Democratic Republic",
  LAT: "Latvia",
  LBA: "Libya",
  LBN: "Lebanon",
  LBR: "Liberia",
  LCA: "Saint Lucia",
  LES: "Lesotho",
  LTU: "Lithuania",
  LUX: "Luxembourg",
  MAD: "Madagascar",
  MAR: "Morocco",
  MAS: "Malaysia",
  MAW: "Malawi",
  MDA: "Moldova (Republic of)",
  MDV: "Maldives",
  MEX: "Mexico",
  MGL: "Mongolia",
  MHL: "Marshall Islands",
  MKD: "North Macedonia",
  MLI: "Mali",
  MLT: "Malta",
  MNE: "Montenegro",
  MOZ: "Mozambique",
  MRI: "Mauritius",
  MTN: "Mauritania",
  MYA: "Myanmar",
  NAM: "Namibia",
  NCA: "Nicaragua",
  NED: "Netherlands",
  NEP: "Nepal",
  NGR: "Nigeria",
  NIG: "Niger",
  NOR: "Norway",
  OMA: "Oman",
  PAK: "Pakistan",
  PAN: "Panama",
  PAR: "Paraguay",
  PER: "Peru",
  PHI: "Philippines",
  PLE: "Palestine",
  PNG: "Papua New Guinea",
  POL: "Poland",
  POR: "Portugal",
  PUR: "Puerto Rico",
  QAT: "Qatar",
  ROU: "Romania",
  RSA: "South Africa",
  RUS: "Russian Federation",
  RWA: "Rwanda",
  SEN: "Senegal",
  SEY: "Seychelles",
  SKN: "Saint Kitts and Nevis",
  SLE: "Sierra Leone",
  SLO: "Slovenia",
  SOL: "Solomon Islands",
  SOM: "Somalia",
  SRB: "Serbia",
  SRI: "Sri Lanka",
  SSD: "South Sudan",
  STP: "Sao Tome and Principe",
  SUD: "Sudan",
  SVK: "Slovakia",
  SWE: "Sweden",
  SWZ: "Eswatini",
  SYR: "Syrian Arab Republic",
  TAN: "Tanzania (United Republic of)",
  TGA: "Tonga",
  THA: "Thailand",
  TJK: "Tajikistan",
  TKM: "Turkmenistan",
  TLS: "Timor-Leste",
  TOG: "Togo",
  TPE: "Chinese Taipei",
  TTO: "Trinidad and Tobago",
  TUN: "Tunisia",
  TUR: "Türkiye",
  UAE: "United Arab Emirates",
  UGA: "Uganda",
  UKR: "Ukraine",
  URU: "Uruguay",
  USA: "United States of America",
  UZB: "Uzbekistan",
  VAN: "Vanuatu",
  VEN: "Venezuela",
  VIE: "Vietnam",
  VIN: "Saint Vincent and the Grenadines",
  YEM: "Yemen",
  ZAM: "Zambia",
  ZIM: "Zimbabwe"
});

/** Équipes inscrites sans code dans les résultats officiels (pas encore de match). */
const UNCODED_TEAMS = [
  "Andorra",
  "Armenia",
  "Bahamas",
  "Bahrain",
  "Bermuda",
  "Burundi",
  "Cyprus",
  "Iceland",
  "Korea (Democratic People's Republic of)",
  "Kuwait",
  "Liechtenstein",
  "Monaco",
  "Nauru",
  "New Zealand",
  "Palau",
  "Samoa",
  "San Marino",
  "Saudi Arabia",
  "Singapore",
  "Suriname",
  "Switzerland",
  "Tuvalu"
];

/**
 * Équipes nationales inscrites au FGC 2026, telles qu'écrites par FIRST Global
 * (carte des équipes de first.global/fgc), triées. Les noms des résultats officiels
 * absents de cette liste sont ajoutés automatiquement à la liste déroulante.
 */
export const TEAMS = Object.freeze([...new Set([...Object.values(TEAM_CODES), ...UNCODED_TEAMS])].sort((a, b) => a.localeCompare(b, "en")));
